services:
  - type: web
    name: crypto-trading-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: KUCOIN_API_KEY
        value: "687d0016c714e80001eecdbe"
      - key: KUCOIN_API_SECRET
        value: "d954b08b-7fbd-408e-a117-4e358a8a764d"
      - key: KUCOIN_API_PASSPHRASE
        value: "Evgeniy@84"
      - key: TELEGRAM_TOKEN
        value: "7630671081:AAG17gVyITruoH_CYreudyTBm5RTpvNgwMA"
      - key: TELEGRAM_CHAT_ID
        value: "5723086631"
